// Static placeholder data shown while Sanity CMS has no content yet.
// Once you add real entries in the Sanity Studio, the site fetches those instead.

export const placeholderArticles = [
  {
    _id: "ph-1",
    titleEn: "How to Actually Use Office Hours",
    titleAr: "كيف تستفيد فعلاً من ساعات المكتب",
    excerptEn: "Most students never go. The ones who do are the ones professors remember. Here's what it actually looks like — and what to say.",
    slug: { current: "how-to-use-office-hours" },
    stage: 4,
    category: "University Life",
    authorName: "The Author",
  },
  {
    _id: "ph-2",
    titleEn: "Picking Your A-Level Subjects",
    titleAr: "اختيار مواد A-Level الخاصة بك",
    excerptEn: "No one told me that picking the wrong combination could close doors before I even knew they existed. Here's a practical framework.",
    slug: { current: "picking-a-level-subjects" },
    stage: 2,
    category: "Exams & Qualifications",
    authorName: "The Author",
  },
  {
    _id: "ph-3",
    titleEn: "What Extracurriculars Actually Signal to Universities",
    titleAr: "ما الذي تعكسه الأنشطة اللاصفية للجامعات فعلاً",
    excerptEn: "Joining thirty clubs and padding your CV doesn't work. Depth beats breadth, every time. Here's how to think about it.",
    slug: { current: "extracurriculars-signal" },
    stage: 2,
    category: "Applications",
    authorName: "The Author",
  },
  {
    _id: "ph-4",
    titleEn: "Writing a Personal Statement That Sounds Like You",
    titleAr: "كتابة بيان شخصي يعبّر عنك فعلاً",
    excerptEn: "The most common mistake is trying to sound impressive. Universities read thousands of these. Here's how to write one they'll remember.",
    slug: { current: "writing-personal-statement" },
    stage: 3,
    category: "Applications",
    authorName: "The Author",
  },
  {
    _id: "ph-5",
    titleEn: "Your First Week at University",
    titleAr: "أسبوعك الأول في الجامعة",
    excerptEn: "Freshers' week is chaotic and slightly overwhelming. Here's what to prioritise and what you can safely ignore.",
    slug: { current: "first-week-university" },
    stage: 4,
    category: "University Life",
    authorName: "The Author",
  },
  {
    _id: "ph-6",
    titleEn: "Setting Up LinkedIn Before You Graduate",
    titleAr: "إنشاء حساب LinkedIn قبل تخرجك",
    excerptEn: "Most people do this too late. If you're in your final year with an empty LinkedIn, you're already behind. Here's what actually matters.",
    slug: { current: "setting-up-linkedin" },
    stage: 5,
    category: "Career",
    authorName: "The Author",
  },
];

export const placeholderBlogEntries = [
  {
    _id: "blog-1",
    title: "Medicine in the UK: What Nobody Told Me Before I Applied",
    slug: { current: "medicine-uk-what-nobody-told-me" },
    authorName: "Fatima Al-Rashid",
    career: "Junior Doctor",
    countryOfStudy: "United Kingdom",
    bio: "Fatima graduated from the University of Manchester Medical School in 2023 and is now a foundation doctor in the NHS.",
    publishedAt: "2024-09-10T00:00:00Z",
    body: [
      {
        _type: "block",
        _key: "b1",
        children: [{ _type: "span", _key: "s1", text: "I applied to medicine without fully understanding what I was signing up for. Not the course — I knew that was hard. I mean the life that comes after. The rota, the hierarchy, the emotional weight of a bad shift. But I also wouldn't trade it. Here's what I'd tell my 17-year-old self." }],
        markDefs: [],
        style: "normal",
      },
    ],
  },
  {
    _id: "blog-2",
    title: "Architecture School: Five Years, No Sleep, Worth It",
    slug: { current: "architecture-school-five-years" },
    authorName: "James Okeke",
    career: "Architectural Assistant",
    countryOfStudy: "United Kingdom",
    bio: "James studied at the Bartlett School of Architecture and is now working at a mid-sized practice in London while completing his Part 2.",
    publishedAt: "2024-10-05T00:00:00Z",
    body: [
      {
        _type: "block",
        _key: "b1",
        children: [{ _type: "span", _key: "s1", text: "I'll be honest: nobody going into architecture school knows how long it actually takes. You think it's three years and you're an architect. It's closer to seven, minimum. But the work changes you in ways that are hard to describe until you're in it. A normal Tuesday for me involves client meetings, model-making, and arguing about why a wall needs to be ten centimetres to the left." }],
        markDefs: [],
        style: "normal",
      },
    ],
  },
  {
    _id: "blog-3",
    title: "From Economics Degree to Investment Banking: The Honest Version",
    slug: { current: "economics-to-investment-banking" },
    authorName: "Sara Mansour",
    career: "Analyst, Investment Banking",
    countryOfStudy: "United States",
    bio: "Sara studied Economics at NYU and joined a bulge-bracket bank straight out of undergrad. She's now in her second year as an analyst.",
    publishedAt: "2024-11-01T00:00:00Z",
    body: [
      {
        _type: "block",
        _key: "b1",
        children: [{ _type: "span", _key: "s1", text: "The version of investment banking I imagined at 18 — suits, Bloomberg terminals, big bonuses — is technically real. But what the recruiting process didn't advertise was the 90-hour weeks, the spreadsheet models you'll redo six times at 1am, or how important Excel shortcuts become to your sense of self-worth. Here's the unfiltered version." }],
        markDefs: [],
        style: "normal",
      },
    ],
  },
];

export const placeholderChecklists = [
  {
    _id: "cl-1",
    titleEn: "Before You Start Researching Universities",
    titleAr: "قبل أن تبدأ بالبحث عن الجامعات",
    slug: { current: "pre-uni-research" },
    stage: 2,
    items: [
      { _key: "i1", textEn: "Know roughly what subjects interest you (even if broadly)", textAr: "تعرّف على المواضيع التي تهمك تقريباً (حتى لو بشكل عام)" },
      { _key: "i2", textEn: "Check what qualifications each country's universities require", textAr: "تحقق من المؤهلات المطلوبة في جامعات كل دولة" },
      { _key: "i3", textEn: "Understand the difference between UCAS, Common App, and other systems", textAr: "افهم الفرق بين UCAS وCommon App وغيرها" },
      { _key: "i4", textEn: "Attend at least one open day before shortlisting", textAr: "احضر يوم مفتوح واحد على الأقل قبل إعداد قائمتك" },
      { _key: "i5", textEn: "Talk to at least one person studying your intended subject", textAr: "تحدث مع شخص واحد على الأقل يدرس التخصص الذي تريده" },
    ],
  },
  {
    _id: "cl-2",
    titleEn: "University Application Checklist",
    titleAr: "قائمة تحقق طلب الالتحاق بالجامعة",
    slug: { current: "university-application" },
    stage: 3,
    items: [
      { _key: "i1", textEn: "Draft your personal statement (at least 3 full drafts)", textAr: "اكتب مسودة بيانك الشخصي (3 مسودات كاملة على الأقل)" },
      { _key: "i2", textEn: "Ask your referee well in advance (minimum 6 weeks)", textAr: "اطلب من مرجعك مسبقاً (6 أسابيع على الأقل)" },
      { _key: "i3", textEn: "Check all application deadlines — they vary by country and institution", textAr: "تحقق من جميع مواعيد التقديم — تختلف حسب الدولة والمؤسسة" },
      { _key: "i4", textEn: "Prepare for any entrance tests (UCAT, LNAT, TSA, SAT, etc.)", textAr: "استعد لأي اختبارات قبول (UCAT وLNAT وTSA وSAT وغيرها)" },
      { _key: "i5", textEn: "Proof-read your application — more than once, ideally by someone else too", textAr: "راجع طلبك بعناية — أكثر من مرة، ويُستحسن أن يراجعه شخص آخر أيضاً" },
      { _key: "i6", textEn: "Understand your student finance options before accepting an offer", textAr: "افهم خيارات التمويل الطلابي قبل قبول أي عرض" },
    ],
  },
  {
    _id: "cl-3",
    titleEn: "Packing for University Halls",
    titleAr: "التحضير للسكن الجامعي",
    slug: { current: "dorm-packing" },
    stage: 4,
    items: [
      { _key: "i1", textEn: "Bedding (check the mattress size for your specific halls)", textAr: "مفروشات السرير (تحقق من مقاس المرتبة في سكنك تحديداً)" },
      { _key: "i2", textEn: "Laptop and chargers", textAr: "حاسوب محمول وشواحن" },
      { _key: "i3", textEn: "Enough kitchen equipment to cook basic meals (one pan, one pot, a spatula)", textAr: "معدات مطبخ كافية لطهي وجبات بسيطة (مقلاة وقدر وملعقة)" },
      { _key: "i4", textEn: "Medication you take regularly, with enough supply for 3 months", textAr: "الأدوية التي تتناولها بانتظام، بمخزون يكفي 3 أشهر" },
      { _key: "i5", textEn: "Important documents: passport, birth certificate, financial docs", textAr: "وثائق مهمة: جواز السفر وشهادة الميلاد والوثائق المالية" },
      { _key: "i6", textEn: "Power strip / extension lead (most halls have limited plug sockets)", textAr: "وصلة كهربائية (معظم مساكن الجامعة لديها مقابس محدودة)" },
    ],
  },
  {
    _id: "cl-4",
    titleEn: "Your First Month at University",
    titleAr: "شهرك الأول في الجامعة",
    slug: { current: "first-month-university" },
    stage: 4,
    items: [
      { _key: "i1", textEn: "Register with a local GP (doctor) as early as possible", textAr: "سجّل لدى طبيب عام محلي في أقرب وقت ممكن" },
      { _key: "i2", textEn: "Open a bank account if you haven't already", textAr: "افتح حساباً مصرفياً إن لم تكن قد فعلت ذلك بعد" },
      { _key: "i3", textEn: "Attend your department's induction / welcome events", textAr: "احضر فعاليات التعريف والاستقبال في قسمك" },
      { _key: "i4", textEn: "Go to at least three society or club events — keep what sticks", textAr: "احضر فعاليات ثلاثة أندية أو جمعيات على الأقل — احتفظ بما يناسبك" },
      { _key: "i5", textEn: "Email one lecturer or attend one office hour in your first two weeks", textAr: "راسل أستاذاً واحداً أو احضر ساعة مكتب واحدة في أسبوعيك الأولين" },
      { _key: "i6", textEn: "Establish a basic routine before lectures get heavy", textAr: "أنشئ روتيناً أساسياً قبل أن تثقل عليك المحاضرات" },
    ],
  },
];

export const placeholderMilestones = [
  {
    _id: "ms-1",
    order: 1,
    gradeLabel: "Grade 9",
    titleEn: "The Foundation Year",
    titleAr: "سنة الأساس",
    summaryEn: "Form your study habits now — they compound. Focus on a small number of extracurriculars you actually care about. Start reading widely outside school.",
    summaryAr: "شكّل عادات دراستك الآن — فهي تتراكم. ركّز على عدد محدود من الأنشطة التي تهتم بها فعلاً. ابدأ بالقراءة الواسعة خارج نطاق المدرسة.",
  },
  {
    _id: "ms-2",
    order: 2,
    gradeLabel: "Grade 10",
    titleEn: "Build the Basics",
    titleAr: "بناء الأسس",
    summaryEn: "Core exams are approaching. Get on top of time management. Learn to cook at least five meals. Begin thinking loosely about what excites you — no commitment needed yet.",
    summaryAr: "الامتحانات الأساسية تقترب. تحكّم في إدارة وقتك. تعلّم طهي خمس وجبات على الأقل. ابدأ بالتفكير بشكل عام فيما يثير اهتمامك — لا حاجة للالتزام بشيء بعد.",
  },
  {
    _id: "ms-3",
    order: 3,
    gradeLabel: "Grade 11",
    titleEn: "First Major Exams",
    titleAr: "أول امتحانات رئيسية",
    summaryEn: "GCSEs, IGCSEs, or equivalents. These don't define you but they do open or close doors. Begin researching what sixth form or pre-university options exist.",
    summaryAr: "GCSEs أو IGCSEs أو ما يعادلها. هذه لا تحدد مصيرك لكنها تفتح أبواباً أو تغلقها. ابدأ بالبحث عن خيارات السنة السادسة أو ما قبل الجامعة.",
  },
  {
    _id: "ms-4",
    order: 4,
    gradeLabel: "Grade 12",
    titleEn: "Sixth Form Begins",
    titleAr: "بداية السنة السادسة",
    summaryEn: "A-Levels, IB, SAT prep, or equivalent. Choose wisely — know which qualifications your target universities accept. Start shortlisting universities and attending open days.",
    summaryAr: "A-Levels أو IB أو التحضير للـSAT أو ما يعادلها. اختر بحكمة — اعرف أي المؤهلات تقبلها الجامعات التي تستهدفها. ابدأ بإعداد قائمة مختصرة من الجامعات وحضور الأيام المفتوحة.",
  },
  {
    _id: "ms-5",
    order: 5,
    gradeLabel: "Grade 13",
    titleEn: "Applications & Final Exams",
    titleAr: "التقديمات والامتحانات النهائية",
    summaryEn: "Personal statements, reference letters, deadlines. Submit applications before you feel ready — because you never will. Sit your final exams without losing perspective.",
    summaryAr: "البيانات الشخصية وخطابات التوصية والمواعيد النهائية. قدّم طلباتك قبل أن تشعر بالاستعداد — لأنك لن تشعر بذلك أبداً. اجتز امتحاناتك النهائية دون أن تفقد نظرتك الشاملة.",
  },
  {
    _id: "ms-6",
    order: 6,
    gradeLabel: "University Year 1",
    titleEn: "Arrive, Adjust, Begin",
    titleAr: "الوصول والتكيّف والبداية",
    summaryEn: "Settle in before you optimise. Meet people. Go to office hours even though it feels awkward. Register for societies. Don't skip the first weeks of lectures.",
    summaryAr: "استقر قبل أن تبدأ بالتحسين. تعرّف على الناس. احضر ساعات المكتب حتى لو بدا الأمر محرجاً. سجّل في الأندية والجمعيات. لا تغب عن محاضرات الأسابيع الأولى.",
  },
  {
    _id: "ms-7",
    order: 7,
    gradeLabel: "University Years 2–3",
    titleEn: "Deepen, Apply, Explore",
    titleAr: "التعمّق والتطبيق والاستكشاف",
    summaryEn: "Internships, dissertation planning, module choices that shape your degree. Start building your professional presence. Don't wait until final year.",
    summaryAr: "التدريب وتخطيط أطروحة التخرج واختيار المقررات التي تشكّل مسار تخرجك. ابدأ ببناء حضورك المهني. لا تنتظر حتى السنة الأخيرة.",
  },
  {
    _id: "ms-8",
    order: 8,
    gradeLabel: "Graduation",
    titleEn: "What Comes Next",
    titleAr: "ما الذي يأتي بعد ذلك",
    summaryEn: "Graduate roles, further study, gap years — all valid. The people who do well in the first year after graduation are usually the ones who started thinking about it in year two.",
    summaryAr: "الوظائف بعد التخرج أو الدراسات العليا أو سنة التوقف — كلها خيارات مشروعة. الأشخاص الذين ينجحون في السنة الأولى بعد التخرج هم عادةً من بدأوا بالتفكير في ذلك في السنة الثانية.",
  },
];

export const placeholderResources = [
  { _id: "r-1", title: "Deep Work", type: "book", author: "Cal Newport", description: "The case for focused, distraction-free work — and how to do it. Essential reading before university.", stage: 1, category: "Study Skills", url: "#" },
  { _id: "r-2", title: "How to Win at College", type: "book", author: "Cal Newport", description: "Simple rules, many of which apply from sixth form onwards. Practical and fast to read.", stage: 2, category: "Study Skills", url: "#" },
  { _id: "r-3", title: "The Pathless Path", type: "book", author: "Paul Millerd", description: "A useful counterweight when everyone around you seems very certain about their career path and you aren't.", stage: 5, category: "Career", url: "#" },
  { _id: "r-4", title: "Ali Abdaal's YouTube Channel", type: "video", author: "Ali Abdaal", description: "A former Cambridge medic who documents study strategies, productivity, and career thinking. Particularly useful for sixth form and early university.", stage: 2, category: "Study Skills", url: "#" },
  { _id: "r-5", title: "80,000 Hours Podcast", type: "podcast", author: "80,000 Hours", description: "Long-form career conversations with researchers, professionals, and thinkers. Makes you think harder about what you actually want from work.", stage: 5, category: "Career", url: "#" },
  { _id: "r-6", title: "UCAS: How It Works", type: "article", author: "UCAS", description: "The official guide to the UK application system. Read the whole thing before you start writing your personal statement.", stage: 3, category: "Applications", url: "#" },
  { _id: "r-7", title: "The Common App Guide", type: "article", author: "Common App", description: "Official walkthrough of the US application system — sections, essays, requirements.", stage: 3, category: "Applications", url: "#" },
  { _id: "r-8", title: "Thinking, Fast and Slow", type: "book", author: "Daniel Kahneman", description: "Not study advice — something broader. Helps you understand how you make decisions, which turns out to matter quite a lot.", stage: 0, category: "General Reading", url: "#" },
  { _id: "r-9", title: "The Tim Ferriss Show", type: "podcast", author: "Tim Ferriss", description: "Long interviews with high performers across fields. A good way to see different career paths from people who've done them.", stage: 5, category: "Career", url: "#" },
  { _id: "r-10", title: "Student Loans: What You Need to Know (UK)", type: "article", author: "MoneySavingExpert", description: "A plain-English breakdown of how UK student finance works, including interest rates and repayment thresholds.", stage: 3, category: "Finance", url: "#" },
];

export const STAGES = [
  { number: 1, slug: "before-sixth-form" },
  { number: 2, slug: "sixth-form" },
  { number: 3, slug: "applications" },
  { number: 4, slug: "university-life" },
  { number: 5, slug: "building-your-future" },
];
